### ISSUE TITLE
Client does not gracfully shut down

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion_api#18]
Test setup: Simple application that imports the javaapi jar; main() instantiates javaapi, calls an api function, and exits. 

When destroyApi() is called, client threads are still running in the threadpool. Need to setup corrent thread exit coditions in MsgExecutor. 

```
18-05-12 15:14:08.320 INFO  BSE  [main]: [destroyApi] Api destroyed
18-05-12 15:14:08.722 INFO  EXE  [msg-exec]: [run] Socket disconnected!
18-05-12 15:14:09.722 ERROR EXE  [pool-6-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-05-12 15:14:11.224 ERROR EXE  [pool-6-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-05-12 15:14:12.726 ERROR EXE  [pool-6-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-05-12 15:14:13.227 WARN  EXE  [pool-6-thread-1]: Heartbeat Timeout, disconnect the connection!
Exception in thread "pool-6-thread-2" org.zeromq.ZMQException: Context was terminated(0x9523dfd)
	at org.zeromq.ZMQ$Socket.recv(Native Method)
	at org.aion.api.impl.MsgExecutor.callbackRun(MsgExecutor.java:485)
	at org.aion.api.impl.MsgExecutor.lambda$run$2(MsgExecutor.java:396)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

![image](https://user-images.githubusercontent.com/23742812/39960908-547d0de2-55f9-11e8-8374-05a11f461aa9.png)

Notice the following threads: 
CallbackRun
HeartBeatRun
WorkerRun

This is the state of the threads at a breakpoint right after the call to api.destroyApi(). 

Added thread names by using Thread.currentThread().setName() on the workerRun(Context ctx), callbackRun(Context ctx) & heartbeatRun(Context ctx) functions, etc.

**Comment by ali-sharif** [comment]
![image](https://user-images.githubusercontent.com/23742812/39960966-8acd6fda-55fa-11e8-913b-ffde6ae3a654.png)

Testcase (breakpoint on the last line, right before exiting):
```
for (int i=0; i<10; i++) {
            System.out.println("run TestGetBlocksDetailsByRange.");

            IAionAPI api = IAionAPI.init();
            api.connect(url);

            long t0 = System.currentTimeMillis();

            ApiMsg msg = api.getAdmin().getBlockDetailsByRange(1L, 500L);
            assertFalse(msg.isError());
            List<BlockDetails> blks = msg.getObject();

            long t1 = System.currentTimeMillis();

            long totalTime = t1 - t0;
            long totalTxns = 0;
            for (BlockDetails b : blks) {
                System.out.println("#: " + b.getNumber() + " [" + b.getTxDetails().size() + "]");
                totalTxns += b.getTxDetails().size();
            }

            System.out.println("bench: " + (t1 - t0) + " ms");
            System.out.println("time/txn: " + totalTime / (double) totalTxns);

            assertNotNull(blks);

            api.destroyApi();

            System.out.println("Api Destroyed");
        }

        System.out.println("test done");
```

**Comment by ali-sharif** [comment]
Furthermore, fix https://github.com/aionnetwork/aion_api/commit/f1278956759cf388ccc00f3eed76112c15c70f72 causes a regression with the heartbeat timeout behaviour: 

Upon heartbeat timeout, any outstanding client calls threw an exception. After this fix, heartbeat timeout no longer causes the client calls to throw an exception to let the caller know that they will not hear back from the server as they have been disconnected.

**Comment by ali-sharif** [comment]
resolved
