### ISSUE TITLE
Java api client causes application to shutdown

### ISSUE THREAD

**Issue by ali-sharif** [aionnetwork/aion_api#26]
Sample Application: [app-template.zip](https://github.com/aionnetwork/aion_api/files/2064066/app-template.zip)

To reproduce:

1. Run the attached application that makes blockDetailsRange calls to kernel on repeat. 
2. In the kernel, in the getBlockDetailsByRange() method, put a thread.sleep(30s)
3. As soon as the thread.sleep is invoked, force shut down the kernel
4. If you do this 3-4 times, at least one of the times, the application will ungracefully exit

Stacktrace when application unexpectedly crashes:
```
run TestGetBlocksDetailsByRange.
18-06-01 16:40:22.011 INFO  BSE  [main]: [connect] Api connected
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/nuco/alisharif/nuco/aion-javaapi/app-template/lib/protobuf-java-3.5.0.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
18-06-01 16:40:26.559 ERROR EXE  [pool-2-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-06-01 16:40:28.063 ERROR EXE  [pool-2-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-06-01 16:40:29.565 ERROR EXE  [pool-2-thread-1]: [checkHbRspMsg] Invalid msg header length!
18-06-01 16:40:30.066 WARN  EXE  [pool-2-thread-1]: Heartbeat Timeout, disconnect the connection!
18-06-01 16:40:31.045 INFO  EXE  [pool-2-thread-3]: worker closing!
18-06-01 16:40:31.046 INFO  EXE  [pool-2-thread-3]: worker closed!
18-06-01 16:40:31.052 INFO  EXE  [pool-2-thread-2]: Callback worker closing!
18-06-01 16:40:31.053 INFO  EXE  [pool-2-thread-2]: Callback worker closed!
18-06-01 16:40:31.564 INFO  EXE  [msg-exec]: [run] Socket disconnected!
18-06-01 16:40:33.070 INFO  EXE  [pool-2-thread-1]: Heartbeat worker closed!
Assertion failed: pfd.revents & POLLIN (src/signaler.cpp:249)
#0  0xfec73958c7d0 in ? (zmq::zmq_abort(char const*)+0x9)
#1  0x7f6371597f29 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libzmq.so.5 (zmq::signaler_t::wait(int)+0x1c7)
#2  0x7f637157dd87 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libzmq.so.5 (zmq::mailbox_t::recv(zmq::command_t*, int)+0x132)
#3  0x7f6371599e22 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libzmq.so.5 (zmq::socket_base_t::process_commands(int, bool)+0x52)
#4  0x7f637159a602 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libzmq.so.5 (zmq::socket_base_t::recv(zmq::msg_t*, int)+0x15b)
#5  0x7f63715b674b in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libzmq.so.5 (s_recvmsg(zmq::socket_base_t*, zmq_msg_t*, int)+0x9)
#6  0x7f6370968859 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libjzmq.so (do_read(JNIEnv_*, _jobject*, zmq_msg_t*, int)+0x40)
#7  0x7f6370969880 in /home/nuco/alisharif/nuco/aion-javaapi/app-template/native/linux/zmq/libjzmq.so (Java_org_zeromq_ZMQ_00024Socket_recv__I+0x29)
#8  0x7f63ad3eab79 in ? (+0x29)
#9  0x7f63ad3e4ce9 in ? (+0x29)
#10  0x7f63ad3e4ce9 in ? (+0x29)
#11  0x7f63ad3e4dbf in ? (+0x29)
#12  0x7f63ad3dbb72 in ? (+0x29)
#13  0x7f63cd9b0869 in /home/nuco/alisharif/bin/jdk-10.0.1/lib/server/libjvm.so (JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x412)
#14  0x7f63cda1ee52 in /home/nuco/alisharif/bin/jdk-10.0.1/lib/server/libjvm.so (jni_invoke_static(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) [clone .isra.86]+0x21f)
#15  0x7f63cda3206f in /home/nuco/alisharif/bin/jdk-10.0.1/lib/server/libjvm.so (jni_CallStaticVoidMethod+0x1a7)
#16  0x7f63ceb6bb97 in /home/nuco/alisharif/bin/jdk-10.0.1/bin/../lib/jli/libjli.so (JavaMain+0xa29)
#17  0x7f63ced7f029 in /lib/x86_64-linux-gnu/libpthread.so.0 (start_thread+0xdb)
#18  0x7f63ce694964 in /lib/x86_64-linux-gnu/libc.so.6 (clone+0x3f)

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by AionJayT** [comment]
fixed in ca2918e30be3d36cf3c657a9437172bb8f93c998
